### ISSUE TITLE
Directory "Data" should be renamed to "data"

### ISSUE THREAD

**Issue by nedhorning** [GatorGlaciology/gstatsimbook#2]
The "Data" directory should be renamed to "data" to be compatible with the Jupyer notebooks.

The first line in code block 3 of Notebook 9_cokriging_and_cosimulation_MM1.ipynb  the line with ‘Data/greenland_surface_data.csv’ should be changed to ‘data/greenland_surface_data.csv’

**Comment by GatorGlaciology** [comment]
done! thanks for flagging this
